import Link from 'next/link'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className='nav'>
          <div className='nav-item'>
            <Link href={'/'}>Home</Link>
          </div>
          <div className='nav-item'>
            <Link href={'/list'}>List</Link>
          </div>
          <div className='nav-item'>
            <Link href={'/new'}>New</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
